version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: data-base-lw4
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: course
      MYSQL_USER: cetus
      MYSQL_PASSWORD: cetuspass
    volumes:
      - mysql_lab_data:/var/lib/mysql

volumes:
  mysql_lab_data: